gregdardis/stock-market-search

- .eslintrc
- src/client/components/definition/definition.css
- src/client/components/definition/definitionData.js
- src/client/components/glossary/Glossary.jsx
- src/client/components/glossary/glossary.css
Turns out doing as much of adding a new line to a string here is a huge pain in the butt. I think that is because html ignores white space. I think it looks okay for now, up to you if you have any ideas to improve it. 
I am no graphic designer
> a bit of glossary formatting

- package.json
> using babel-watch to watch files

- src/client/components/chart/Chart.jsx
> formatted price on tootltip properly

- src/client/components/search/Search.jsx
> disabled spellcheck in search bar

- src/client/reducers/search.js
> auto-capitalize search bar content

- src/client/actions/index.js
- src/client/actions/stock.js
- src/client/components/home/Home.jsx
- src/client/components/home/index.js
- src/client/components/search/Search.jsx
- src/client/components/search/index.js
- src/client/components/searchLoader/SearchLoader.jsx
- src/client/components/searchLoader/index.js
- src/client/reducers/selectedStock.js
- src/constants/index.js
- src/utils/stateGetters/index.js
When a stock is searched, we first see if we have its data in memory (i.e. in the redux state).
If we do, show the user the out of date info.
Then whether we do or not, fetch the up-to-date info and display it.
close #95
> Cached stock

- README.md
> updated README, removed work in progress

- src/client/components/search/search.css
- src/client/index.html
Fixes #103 
Reference: https://stackoverflow.com/questions/5939341/firefox-4-is-there-a-way-to-remove-the-red-border-in-a-required-form-input/18224134
> Fix firefox red input border

- src/client/components/definition/Definition.jsx
- src/client/components/definition/definitionData.js
- src/client/components/glossary/Glossary.jsx
- src/client/index.html
Implements #68 
Wrote LaTeX formulas which are interpreted by https://www.mathjax.org/ for the glossary math equations.
Used a CDN for MathJax, which should update to latest version each time one is released, not just get version 2.7.5 like is written in the CDN src.
> Style math equations

- .babelrc
- .eslintrc
- mocha.env.js
- mocha.opts
- package-lock.json
- package.json
- src/utils/dateUtils/dateCalculations.js
- src/utils/dateUtils/dateCalculations.test.js
- src/utils/typeChecking.js
- src/utils/typeChecking.test.js
Tests are in dateCalculations.test.js
> Wrote tests for dateCalculations.js

- src/utils/stockDataUtils/calculations.test.js
#134 checkbox 2: stub out parseIntExact in src/utils/stockDataUtils/calculations.test.js
> stubbed parseIntExact in calculations.test.js

- src/client/components/search/Search.jsx
> clear search errors when user presses search

- package.json
> excluded some files from coverage

- package-lock.json
- package.json
- src/client/components/chart/index.test.js
- src/client/components/companyNameAndSymbol/CompanyNameAndSymbol.test.jsx
- src/client/components/companyNameAndSymbol/index.js
- src/client/components/companyNameAndSymbol/index.test.js
- src/client/components/exchange/index.test.js
- src/client/reducers/index.test.js
- src/client/selectors.js
Checks a box in #137.
Also begins the work for #170.
> Test company name and symbol

- src/client/selectors.test.js
> Test reselect selectors

- src/client/components/glossary/Glossary.jsx
- src/client/components/glossary/Glossary.test.jsx
Also:
- updated tests to handle additional case
- changed jest assertions to chai-enzyme ones
> Refactored Glossary to take definitions as prop

- .eslintrc
> changed no-debugger back to error

- src/utils/dateUtils/dateCalculations.js
- src/utils/dateUtils/dateCalculations.test.js
- src/utils/parseIntExact.js
- src/utils/parseIntExact.test.js
- src/utils/stockDataUtils/calculations.js
- src/utils/stockDataUtils/calculations.test.js
- src/utils/typeChecking.js
- src/utils/typeChecking.test.js
Implements #141.
Name of file good or is there a better utils category it could go in?
> extracted parseIntExact to its own file

- package-lock.json
- package.json
- src/utils/dateUtils/dateFormatting.js
Thoughts on if I put all the dev dependencies in devDependencies? Reason for doing this is I think it makes the bundle smaller for production if you don't have extra dependencies that are only for development.
Fixes #152
> reorganized dependencies, fixed lint error in dateFormatting

- src/client/components/appWrapper/AppWrapper.test.jsx
- src/client/components/chart/Chart.test.jsx
- src/client/components/search/Search.test.jsx
- src/client/components/timePeriodButtons/TimePeriodButtons.jsx
- src/client/components/timePeriodButtons/TimePeriodButtons.test.jsx
- src/client/reducers/chartTimePeriodIndex.js
- src/client/reducers/chartTimePeriodIndex.test.js
- src/constants/formatting.js
- src/utils/chartUtils.js
- src/utils/chartUtils.test.js
- src/utils/stockDataUtils/getStockDataForSelectedTimePeriod.js
> Refactor expects

- src/client/components/chart/Chart.jsx
> set connectNulls to true for chart line

- features/page-objects/glossary.js
- features/page-objects/home.js
- features/search.feature
- features/shared-objects/constants.js
- features/step-definitions/glossary-steps.js
- features/step-definitions/search.steps.js
- features/step-definitions/shared-steps.js
Work for #138
Also refactored to make use of page-objects and shared-steps.js.
> Wrote BVT for stock not found
